= About this repository

This repository is an example project to illustrate how to use `commanduunit` https://github.com/dakusui/commandunit[github] and how to organize a shell script based project using it.

To just run tests under `src/main/scripts`, type the following command from your terminal:

----
./build.sh
----

Note that you need a docker CLI installed, and docker daemon running.
Also, we tested this repository with `bash 5.1` (Ubuntu 22.04).

On a "successful" execution, it will show:

----
$ ./build.sh
1..8
# Processing 'yaml++' files.
ok # skip 1 process file: 'core/test-abort.yaml++'
ok # skip 2 process file: 'core/test-assert-false.yaml++'
ok 3 process file: core/test-cat-failing.yaml++)
ok # skip 4 process file: 'core/test-cat.yaml++'
ok # skip 5 process file: 'core/test-is_void_value-false.yaml++'
ok # skip 6 process file: 'core/test-is_void_value-true.yaml++'
ok # skip 7 process file: 'core/test-set.yaml++'
ok # skip 8 process file: 'core/test-void_value.yaml++'
1..0
# Processing 'yaml' files.
1..8
# Processing 'json++' files.
ok # skip 1 process file: 'core/test-abort.json++'
ok # skip 2 process file: 'core/test-assert-false.json++'
ok 3 process file: core/test-cat-failing.json++)
ok # skip 4 process file: 'core/test-cat.json++'
ok # skip 5 process file: 'core/test-is_void_value-false.json++'
ok # skip 6 process file: 'core/test-is_void_value-true.json++'
ok # skip 7 process file: 'core/test-set.json++'
ok # skip 8 process file: 'core/test-void_value.json++'
1..8
ok 1 core/test-abort.json
ok 2 core/test-assert-false.json
not ok 3 core/test-cat-failing.json
ok 4 core/test-cat.json
ok 5 core/test-is_void_value-false.json
ok 6 core/test-is_void_value-true.json
ok 7 core/test-set.json
ok 8 core/test-void_value.json
FAILED: CHECK /home/hiroshi/Documents/github/commandunit-example/commandunit-out/report/testreport.adoc
ERROR:(exit code:1, pipe status: 1):
  at /app/dependencies/bud/lib/core.rc:54 (abort)
  at /app/bin/commandunit:189 (main)
----

One test in the example test suite should fail and the command should exit with `1`.
Don't worry, it's just because there is one test is designed to fail intentionally in order to illustrate how a test report looks like.

== Installation of `commandunit`

To try the from your command line, do:

----
. build.sh
----

This will define a bash function whose name is `commandunit` which you can run from your terminal.
In other words, you can use the tool in your project just by copy the definition of the function to your build script.
As long as you have `docker` command available.

[INFO]
====
It is suggested to specify a directory that holds test scripts and directories, where `commandunit` stores its internal data and writes report.
For instance, following is the command line that the `build.sh` executes when it is directly run.

----
commandunit --test-srcdir=./src/test/scripts --test-workdir=./commandunit-out/work  --test-reportdir=./commandunit-out/report
----

This behavior is planned to be improved under this ticket:  https://github.com/dakusui/commandunit/issues/4[improve default values of commandunit]
====

== Design of `commandunit`

The `commandunit` uses `jq-front`(https://dakusui.github.io/jq-front/[jq-front]) to let users write tests.
`jq-front` is a tool that allows you to use inheritances and node references (and more) in JSON files.

When it finds a file ends with `.yaml++`, the tool converts it to a JSON file first and the converted file will have a suffix `.json++'.
Then the `.json++` files will be converted into '.json' file using `jq-front`.

After this preprocessing step is finished, based on the content of the final JSON files, which should contain full-information to execute a test case, `commandunit` executes the test case.

So, familiarizing yourself with `jq-front` 's syntax will be very useful although you can write a test without the knowledge.

== Test Script Format

[source,yaml]
.Example
----
---
"$extends":
  - base/normal.json
when:
  description:
    - Call 'abort' function define in core.rc.
    - This test is to illustrate the usage of the function.
  source:
    - ${COMMANDUNIT_DEPENDENCIES_ROOT}/bud/lib/core.rc
    - ${COMMANDUNIT_HOSTFSROOT_MOUNTPOINT}/${COMMANDUNIT_PWD}/src/main/scripts/target_lib.rc
  cmd: assert_that
  args:
    - HELLO
    - "[["
    - hello
    - ==
    - Hello
    - "]]"
then:
  exitCode:
    - NOT_EQUAL
    - 0
  stdout:
    absent:
      - REGEX:.+
  stderr:
    present:
      - REGEX:Condition.*HELLO
      - REGEX:Detail.*hello.*Hello
----

"$extends"::
This attribute specifies a template of a test definition.
`base/normal.json` is a built-in template.
You can define your own template and specify it here.
The built-in templates avaialbe are found in the `commandunit` 's repository (https://github.com/dakusui/commandunit/tree/main/src/main/scripts/lib/jsonpp/base[built-in templates]).
when::
This section defines what will be exercised in a test.
- description:: An array. You can describe the operation to be verified in this test.
- environmentVariables:: An object. You can store key-value pair whose key is a name of an environment variable.
- source:: An array you can list files to be sourced before the command (`cmd`) is executed.
- cmd:: A string. A command (or more generally an "executable", such as a function) to be executed
- args:: An array. You can list string values to be passed to the command (`cmd`).
then::
This section defines how the exercised operation is verified.
- description:: You can describe how the operation defined in `when` should be verified.
- exitCode:: An array. You can describe the condition that should be satisfied by an exit code of `cmd` in `when` clause.
The first element is a name of a predicate factory and the rest will be arguments passed to the factory.
The exit code will then be checked with the predicated created by the factory.
- stdout:: An object. You can describe the expectation for `stdout` of `cmd` in `when` clause.
Under this object you can place `present` and `absent` attributes.
  - present and absent:: arrays. These attributes define patterns that should present or absent in the target stream (`stdout` or `stderr`).
If you give a string starting with `REGEX:`, the rest will be treated as a regular expression.
If a matching line for a pattern in `present` attribute is find in the target stream, the conditition defined by the string will be considered satisfied.
If and only if all the conditions defined for `present` are satisfied, the target stream will be considered "pass" for `present`.
For `absent`, if and only if none of the conditions defined for it are satisfied, the tatarget stream will be considered "pass".
- sterr:: An object. You can describe the expectation for `stderr` of `cmd` in `when` clause.
For more detail, refer to `stdout`.

== Test Report

In this section, the directory structure and there contents, which `commandunit` writes will be discussed.

== Directory Structure

Following is the directory

----
commandunit-out/
  report/
    {testsuite-directory-name}/
      {testsuite-directory-name}/{testcase-name-1}.json-output/
      {testsuite-directory-name}/{testcase-name-2}.json-output/
  work/
    testreport.adoc
    testreport.json
----

=== Files

----
{testsuite-directory-name}/{testcase-name-#}.json-output/
  execution.txt
  exit_code.txt
  precheck.txt
  script.txt
  stderr.txt
  stdout.txt
----
